[package]
name = "phys_plotter"
description = "Linear data regression and plotting tool"
version = "0.2.2"
authors = ["Zhang Maiyun <myzhang1029@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.bundle.bin.phys_plotter_gui]
name = "Physics Plotter"
identifier = "bike.myzhangll.Physics.Plotter"

[dependencies]
clap = "2.33.3"
gio = "0.9.1"
glib = "0.10.3"
gnuplot = "0.0.37"
gtk = "0.9.2"
plotters = "0.3.0"
plotters-cairo = "0.3.1"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.59"

[lib]
name = "phys_plotter"
path = "src/lib.rs"

[[bin]]
name = "phys_plotter"
path = "src/bin/cli/main.rs"

[[bin]]
name = "phys_plotter_gui"
path = "src/bin/gui/main.rs"
