[package]
name = "phys_plotter"
version = "0.1.0"
authors = ["Zhang Maiyun <myzhang1029@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.37"