[package]
name = "phys_plotter"
version = "0.1.3"
authors = ["Zhang Maiyun <myzhang1029@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
gnuplot = "0.0.37"
gtk = "0.9.2"
plotters = "0.3.0"

[lib]
name = "phys_plotter"
path = "src/lib.rs"

[[bin]]
name = "phys_plotter"
path = "src/bin/cli/main.rs"

[[bin]]
name = "phys_plotter_gui"
path = "src/bin/gui/main.rs"