name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Install gtk+3
    - name: Install dependencies
      run: |
        sudo apt-get -q update
        sudo apt-get install -yq libgtk-3-dev
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo clippy --verbose -- -D warnings
    - name: Run tests
      run: cargo test --verbose
