name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup target add wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=ui_egui --lib --target wasm32-unknown-unknown

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install gtk+3
    - name: Install dependencies
      run: |
        sudo apt-get -q update
        sudo apt-get install -yq libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
    - name: Lint
      run: cargo clippy --verbose -- -D warnings
    - name: Run tests
      run: cargo test --verbose

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Install gtk+3
    - name: Install dependencies
      run: |
        sudo apt-get -q update
        sudo apt-get install -yq libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
    - name: Build
      run: cargo build --verbose --features=ui_gtk,ui_egui

  check_cli_only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup target add wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=ui_cli --no-default-features --lib --target wasm32-unknown-unknown
